# Deploys a Node app to GitHub Pages with either Yarn 2 or NPM
# Also uses a cache to speed up build times
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - src/**
      - '**/*.js*'

env:
  # Name of the script to build the project (eg. `build` for `npm run build`)
  BUILD_SCRIPT: build
  # Directory of the built static files
  BUILD_DIR: dist

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2

      - name: Get Yarn 2 Cache Directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn 2 Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn ${{ env.BUILD_SCRIPT }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.BUILD_DIR }}
